# Generated by Django 3.2.5 on 2021-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encryptKey',
            field=models.CharField(default='abn3@f3vsdr-3', max_length=50),
        ),
    ]
