# Generated by Django 3.2.6 on 2021-08-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_encryptkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='nickName',
        ),
    ]
