# Generated by Django 3.2.6 on 2021-08-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_nick_name_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='token',
            field=models.CharField(max_length=65, primary_key=True, serialize=False),
        ),
    ]
