# Generated by Django 3.2.6 on 2021-08-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210826_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Music',
        ),
    ]
