import 'dart:convert';

import 'package:http/http.dart' as http;

import '../../Models/Music.dart';

List<Music>? apiRequest(String q) {
  // String token = "BQDceTWTrpviayi0DB2hIqzSo0XbyciuMi6gdJ4ocJ2oebGmbmtX-uoyLzvJGv0s1LGd_paEbpuBO_xHA66O5X6zljONAYH8FJOmgYMyhcbaFruHaYI0LJg40l0N1cLY-nRf";
  // final response = await http.get("https://api.spotify.com/v1/search",
  //   headers: {
  //     'q': q,
  //     'type': "track",
  //     'Authorization': 'Bearer $token'
  //   }
  // );
  // Map<String, dynamic> json = jsonDecode(response.body);

  // String testJson = await rootBundle.loadString('json/test.json');
  String test = 
  '''{ "tracks": {
    "href": "https://api.spotify.com/v1/search?query=stay&type=track&offset=0&limit=10",
    "items": [
      {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2tIP7SsRs7vjIcLrU85W8J"
              },
              "href": "https://api.spotify.com/v1/artists/2tIP7SsRs7vjIcLrU85W8J",
              "id": "2tIP7SsRs7vjIcLrU85W8J",
              "name": "The Kid LAROI",
              "type": "artist",
              "uri": "spotify:artist:2tIP7SsRs7vjIcLrU85W8J"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s"
              },
              "href": "https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s",
              "id": "1uNFoZAHBGtllmzznpCI3s",
              "name": "Justin Bieber",
              "type": "artist",
              "uri": "spotify:artist:1uNFoZAHBGtllmzznpCI3s"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4QLAtpLNUsHEYrcHXmMIZZ"
          },
          "href": "https://api.spotify.com/v1/albums/4QLAtpLNUsHEYrcHXmMIZZ",
          "id": "4QLAtpLNUsHEYrcHXmMIZZ",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27341e31d6ea1d493dd77933ee5",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0241e31d6ea1d493dd77933ee5",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485141e31d6ea1d493dd77933ee5",
              "width": 64
            }
          ],
          "name": "STAY (with Justin Bieber)",
          "release_date": "2021-07-09",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:4QLAtpLNUsHEYrcHXmMIZZ"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2tIP7SsRs7vjIcLrU85W8J"
            },
            "href": "https://api.spotify.com/v1/artists/2tIP7SsRs7vjIcLrU85W8J",
            "id": "2tIP7SsRs7vjIcLrU85W8J",
            "name": "The Kid LAROI",
            "type": "artist",
            "uri": "spotify:artist:2tIP7SsRs7vjIcLrU85W8J"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s"
            },
            "href": "https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s",
            "id": "1uNFoZAHBGtllmzznpCI3s",
            "name": "Justin Bieber",
            "type": "artist",
            "uri": "spotify:artist:1uNFoZAHBGtllmzznpCI3s"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 141805,
        "explicit": true,
        "external_ids": {
          "isrc": "USSM12103949"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5HCyWlXZPP0y6Gqq8TgA20"
        },
        "href": "https://api.spotify.com/v1/tracks/5HCyWlXZPP0y6Gqq8TgA20",
        "id": "5HCyWlXZPP0y6Gqq8TgA20",
        "is_local": false,
        "name": "STAY (with Justin Bieber)",
        "popularity": 100,
        "preview_url": "https://p.scdn.co/mp3-preview/dd4d8d66b97b6edcb5358135e72620715e1449f9?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:5HCyWlXZPP0y6Gqq8TgA20"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/246dkjvS1zLTtiykXe5h60"
              },
              "href": "https://api.spotify.com/v1/artists/246dkjvS1zLTtiykXe5h60",
              "id": "246dkjvS1zLTtiykXe5h60",
              "name": "Post Malone",
              "type": "artist",
              "uri": "spotify:artist:246dkjvS1zLTtiykXe5h60"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BZ",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "VC",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/6trNtQUgC8cgbWcqoMYkOR"
          },
          "href": "https://api.spotify.com/v1/albums/6trNtQUgC8cgbWcqoMYkOR",
          "id": "6trNtQUgC8cgbWcqoMYkOR",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273b1c4b76e23414c9f20242268",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02b1c4b76e23414c9f20242268",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851b1c4b76e23414c9f20242268",
              "width": 64
            }
          ],
          "name": "beerbongs & bentleys",
          "release_date": "2018-04-27",
          "release_date_precision": "day",
          "total_tracks": 18,
          "type": "album",
          "uri": "spotify:album:6trNtQUgC8cgbWcqoMYkOR"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/246dkjvS1zLTtiykXe5h60"
            },
            "href": "https://api.spotify.com/v1/artists/246dkjvS1zLTtiykXe5h60",
            "id": "246dkjvS1zLTtiykXe5h60",
            "name": "Post Malone",
            "type": "artist",
            "uri": "spotify:artist:246dkjvS1zLTtiykXe5h60"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 204426,
        "explicit": true,
        "external_ids": {
          "isrc": "USUM71805172"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4H7WNRErSbONkM06blBoGc"
        },
        "href": "https://api.spotify.com/v1/tracks/4H7WNRErSbONkM06blBoGc",
        "id": "4H7WNRErSbONkM06blBoGc",
        "is_local": false,
        "name": "Stay",
        "popularity": 73,
        "preview_url": null,
        "track_number": 12,
        "type": "track",
        "uri": "spotify:track:4H7WNRErSbONkM06blBoGc"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2tIP7SsRs7vjIcLrU85W8J"
              },
              "href": "https://api.spotify.com/v1/artists/2tIP7SsRs7vjIcLrU85W8J",
              "id": "2tIP7SsRs7vjIcLrU85W8J",
              "name": "The Kid LAROI",
              "type": "artist",
              "uri": "spotify:artist:2tIP7SsRs7vjIcLrU85W8J"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4bZJWQhHKJckFLJuYdvyX2"
          },
          "href": "https://api.spotify.com/v1/albums/4bZJWQhHKJckFLJuYdvyX2",
          "id": "4bZJWQhHKJckFLJuYdvyX2",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2738e6551a2944764bc8e33a960",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e028e6551a2944764bc8e33a960",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048518e6551a2944764bc8e33a960",
              "width": 64
            }
          ],
          "name": "F*CK LOVE 3: OVER YOU",
          "release_date": "2021-07-23",
          "release_date_precision": "day",
          "total_tracks": 29,
          "type": "album",
          "uri": "spotify:album:4bZJWQhHKJckFLJuYdvyX2"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2tIP7SsRs7vjIcLrU85W8J"
            },
            "href": "https://api.spotify.com/v1/artists/2tIP7SsRs7vjIcLrU85W8J",
            "id": "2tIP7SsRs7vjIcLrU85W8J",
            "name": "The Kid LAROI",
            "type": "artist",
            "uri": "spotify:artist:2tIP7SsRs7vjIcLrU85W8J"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s"
            },
            "href": "https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s",
            "id": "1uNFoZAHBGtllmzznpCI3s",
            "name": "Justin Bieber",
            "type": "artist",
            "uri": "spotify:artist:1uNFoZAHBGtllmzznpCI3s"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 141805,
        "explicit": true,
        "external_ids": {
          "isrc": "USSM12103949"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5PjdY0CKGZdEuoNab3yDmX"
        },
        "href": "https://api.spotify.com/v1/tracks/5PjdY0CKGZdEuoNab3yDmX",
        "id": "5PjdY0CKGZdEuoNab3yDmX",
        "is_local": false,
        "name": "STAY (with Justin Bieber)",
        "popularity": 90,
        "preview_url": "https://p.scdn.co/mp3-preview/dd4d8d66b97b6edcb5358135e72620715e1449f9?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 3,
        "type": "track",
        "uri": "spotify:track:5PjdY0CKGZdEuoNab3yDmX"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H"
              },
              "href": "https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H",
              "id": "5pKCCKE2ajJHZ9KAiaK11H",
              "name": "Rihanna",
              "type": "artist",
              "uri": "spotify:artist:5pKCCKE2ajJHZ9KAiaK11H"
            }
          ],
          "available_markets": [
            "CA",
            "MX",
            "US"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4eddbruVtOqw8khwxSH6H2"
          },
          "href": "https://api.spotify.com/v1/albums/4eddbruVtOqw8khwxSH6H2",
          "id": "4eddbruVtOqw8khwxSH6H2",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2730e6cedee56e37a9a65f2164d",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e020e6cedee56e37a9a65f2164d",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048510e6cedee56e37a9a65f2164d",
              "width": 64
            }
          ],
          "name": "Unapologetic (Deluxe)",
          "release_date": "2012-12-11",
          "release_date_precision": "day",
          "total_tracks": 17,
          "type": "album",
          "uri": "spotify:album:4eddbruVtOqw8khwxSH6H2"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H"
            },
            "href": "https://api.spotify.com/v1/artists/5pKCCKE2ajJHZ9KAiaK11H",
            "id": "5pKCCKE2ajJHZ9KAiaK11H",
            "name": "Rihanna",
            "type": "artist",
            "uri": "spotify:artist:5pKCCKE2ajJHZ9KAiaK11H"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1buzCmyYZE4kcdLRudsb8V"
            },
            "href": "https://api.spotify.com/v1/artists/1buzCmyYZE4kcdLRudsb8V",
            "id": "1buzCmyYZE4kcdLRudsb8V",
            "name": "Mikky Ekko",
            "type": "artist",
            "uri": "spotify:artist:1buzCmyYZE4kcdLRudsb8V"
          }
        ],
        "available_markets": [
          "CA",
          "MX",
          "US"
        ],
        "disc_number": 1,
        "duration_ms": 240706,
        "explicit": false,
        "external_ids": {
          "isrc": "USUM71214754"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/1dEy9Pl81QopSxNsPxXQxv"
        },
        "href": "https://api.spotify.com/v1/tracks/1dEy9Pl81QopSxNsPxXQxv",
        "id": "1dEy9Pl81QopSxNsPxXQxv",
        "is_local": false,
        "name": "Stay",
        "popularity": 65,
        "preview_url": null,
        "track_number": 9,
        "type": "track",
        "uri": "spotify:track:1dEy9Pl81QopSxNsPxXQxv"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2wY79sveU1sp5g7SokKOiI"
              },
              "href": "https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI",
              "id": "2wY79sveU1sp5g7SokKOiI",
              "name": "Sam Smith",
              "type": "artist",
              "uri": "spotify:artist:2wY79sveU1sp5g7SokKOiI"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JM",
            "JO",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/08jWgM4vSkTose4blKBWov"
          },
          "href": "https://api.spotify.com/v1/albums/08jWgM4vSkTose4blKBWov",
          "id": "08jWgM4vSkTose4blKBWov",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273b11bdc91cb9ac6b14f5c1dae",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02b11bdc91cb9ac6b14f5c1dae",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851b11bdc91cb9ac6b14f5c1dae",
              "width": 64
            }
          ],
          "name": "In The Lonely Hour",
          "release_date": "2014-05-26",
          "release_date_precision": "day",
          "total_tracks": 10,
          "type": "album",
          "uri": "spotify:album:08jWgM4vSkTose4blKBWov"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2wY79sveU1sp5g7SokKOiI"
            },
            "href": "https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI",
            "id": "2wY79sveU1sp5g7SokKOiI",
            "name": "Sam Smith",
            "type": "artist",
            "uri": "spotify:artist:2wY79sveU1sp5g7SokKOiI"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 172723,
        "explicit": false,
        "external_ids": {
          "isrc": "GBUM71308833"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5Nm9ERjJZ5oyfXZTECKmRt"
        },
        "href": "https://api.spotify.com/v1/tracks/5Nm9ERjJZ5oyfXZTECKmRt",
        "id": "5Nm9ERjJZ5oyfXZTECKmRt",
        "is_local": false,
        "name": "Stay With Me",
        "popularity": 81,
        "preview_url": null,
        "track_number": 3,
        "type": "track",
        "uri": "spotify:track:5Nm9ERjJZ5oyfXZTECKmRt"
      },
      {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2tIP7SsRs7vjIcLrU85W8J"
              },
              "href": "https://api.spotify.com/v1/artists/2tIP7SsRs7vjIcLrU85W8J",
              "id": "2tIP7SsRs7vjIcLrU85W8J",
              "name": "The Kid LAROI",
              "type": "artist",
              "uri": "spotify:artist:2tIP7SsRs7vjIcLrU85W8J"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s"
              },
              "href": "https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s",
              "id": "1uNFoZAHBGtllmzznpCI3s",
              "name": "Justin Bieber",
              "type": "artist",
              "uri": "spotify:artist:1uNFoZAHBGtllmzznpCI3s"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JM",
            "JO",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4Lc269uQdu2XPJC1aZBR1E"
          },
          "href": "https://api.spotify.com/v1/albums/4Lc269uQdu2XPJC1aZBR1E",
          "id": "4Lc269uQdu2XPJC1aZBR1E",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273809ac854713e65ce1f4d4bdd",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02809ac854713e65ce1f4d4bdd",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851809ac854713e65ce1f4d4bdd",
              "width": 64
            }
          ],
          "name": "STAY (with Justin Bieber)",
          "release_date": "2021-07-09",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:4Lc269uQdu2XPJC1aZBR1E"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2tIP7SsRs7vjIcLrU85W8J"
            },
            "href": "https://api.spotify.com/v1/artists/2tIP7SsRs7vjIcLrU85W8J",
            "id": "2tIP7SsRs7vjIcLrU85W8J",
            "name": "The Kid LAROI",
            "type": "artist",
            "uri": "spotify:artist:2tIP7SsRs7vjIcLrU85W8J"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s"
            },
            "href": "https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s",
            "id": "1uNFoZAHBGtllmzznpCI3s",
            "name": "Justin Bieber",
            "type": "artist",
            "uri": "spotify:artist:1uNFoZAHBGtllmzznpCI3s"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 141805,
        "explicit": false,
        "external_ids": {
          "isrc": "USSM12104470"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4kux0P5UfguojB4h0lQnsj"
        },
        "href": "https://api.spotify.com/v1/tracks/4kux0P5UfguojB4h0lQnsj",
        "id": "4kux0P5UfguojB4h0lQnsj",
        "is_local": false,
        "name": "STAY (with Justin Bieber)",
        "popularity": 63,
        "preview_url": "https://p.scdn.co/mp3-preview/1c30283216331fac796097433e49d359c4bf8915?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:4kux0P5UfguojB4h0lQnsj"
      },
      {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3ZHU5AKrUmIPnCFfr82QER"
              },
              "href": "https://api.spotify.com/v1/artists/3ZHU5AKrUmIPnCFfr82QER",
              "id": "3ZHU5AKrUmIPnCFfr82QER",
              "name": "1nonly",
              "type": "artist",
              "uri": "spotify:artist:3ZHU5AKrUmIPnCFfr82QER"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/5TPtlK0RBgPloK3Robfiyp"
          },
          "href": "https://api.spotify.com/v1/albums/5TPtlK0RBgPloK3Robfiyp",
          "id": "5TPtlK0RBgPloK3Robfiyp",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273264a0478cccbc94ac61cb479",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02264a0478cccbc94ac61cb479",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851264a0478cccbc94ac61cb479",
              "width": 64
            }
          ],
          "name": "Stay With Me",
          "release_date": "2020-10-11",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:5TPtlK0RBgPloK3Robfiyp"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3ZHU5AKrUmIPnCFfr82QER"
            },
            "href": "https://api.spotify.com/v1/artists/3ZHU5AKrUmIPnCFfr82QER",
            "id": "3ZHU5AKrUmIPnCFfr82QER",
            "name": "1nonly",
            "type": "artist",
            "uri": "spotify:artist:3ZHU5AKrUmIPnCFfr82QER"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 141505,
        "explicit": true,
        "external_ids": {
          "isrc": "TCAFE2016912"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/2WYs5LxOZfEyURXu7V0O1a"
        },
        "href": "https://api.spotify.com/v1/tracks/2WYs5LxOZfEyURXu7V0O1a",
        "id": "2WYs5LxOZfEyURXu7V0O1a",
        "is_local": false,
        "name": "Stay With Me",
        "popularity": 78,
        "preview_url": "https://p.scdn.co/mp3-preview/0fd4ad4b2be170342a73fede6c88a7944e176510?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:2WYs5LxOZfEyURXu7V0O1a"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
              },
              "href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
              "id": "4MCBfE4596Uoi2O4DtmEMz",
              "name": "Juice WRLD",
              "type": "artist",
              "uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/6n9DKpOxwifT5hOXtgLZSL"
          },
          "href": "https://api.spotify.com/v1/albums/6n9DKpOxwifT5hOXtgLZSL",
          "id": "6n9DKpOxwifT5hOXtgLZSL",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2733e0698e4ae5ffb82a005aeeb",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e023e0698e4ae5ffb82a005aeeb",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048513e0698e4ae5ffb82a005aeeb",
              "width": 64
            }
          ],
          "name": "Legends Never Die",
          "release_date": "2020-07-10",
          "release_date_precision": "day",
          "total_tracks": 22,
          "type": "album",
          "uri": "spotify:album:6n9DKpOxwifT5hOXtgLZSL"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
            },
            "href": "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
            "id": "4MCBfE4596Uoi2O4DtmEMz",
            "name": "Juice WRLD",
            "type": "artist",
            "uri": "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 168684,
        "explicit": true,
        "external_ids": {
          "isrc": "USUG12002590"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/21CkzgKCBCq5V4XKjiGSIj"
        },
        "href": "https://api.spotify.com/v1/tracks/21CkzgKCBCq5V4XKjiGSIj",
        "id": "21CkzgKCBCq5V4XKjiGSIj",
        "is_local": false,
        "name": "Stay High",
        "popularity": 74,
        "preview_url": null,
        "track_number": 19,
        "type": "track",
        "uri": "spotify:track:21CkzgKCBCq5V4XKjiGSIj"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4hUmsYcvD8C5zuVSP93jb1"
              },
              "href": "https://api.spotify.com/v1/artists/4hUmsYcvD8C5zuVSP93jb1",
              "id": "4hUmsYcvD8C5zuVSP93jb1",
              "name": "Miki Matsubara",
              "type": "artist",
              "uri": "spotify:artist:4hUmsYcvD8C5zuVSP93jb1"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JM",
            "JO",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1ANaxJNBcbOvvycNL4MCL5"
          },
          "href": "https://api.spotify.com/v1/albums/1ANaxJNBcbOvvycNL4MCL5",
          "id": "1ANaxJNBcbOvvycNL4MCL5",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27381052badd62d5e14c3377786",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0281052badd62d5e14c3377786",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485181052badd62d5e14c3377786",
              "width": 64
            }
          ],
          "name": "Miki Matsubara Best Collection",
          "release_date": "2008",
          "release_date_precision": "year",
          "total_tracks": 17,
          "type": "album",
          "uri": "spotify:album:1ANaxJNBcbOvvycNL4MCL5"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4hUmsYcvD8C5zuVSP93jb1"
            },
            "href": "https://api.spotify.com/v1/artists/4hUmsYcvD8C5zuVSP93jb1",
            "id": "4hUmsYcvD8C5zuVSP93jb1",
            "name": "Miki Matsubara",
            "type": "artist",
            "uri": "spotify:artist:4hUmsYcvD8C5zuVSP93jb1"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 312293,
        "explicit": false,
        "external_ids": {
          "isrc": "JPPC07950030"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/2BHj31ufdEqVK5CkYDp9mA"
        },
        "href": "https://api.spotify.com/v1/tracks/2BHj31ufdEqVK5CkYDp9mA",
        "id": "2BHj31ufdEqVK5CkYDp9mA",
        "is_local": false,
        "name": "Mayonaka no Door / Stay With Me",
        "popularity": 75,
        "preview_url": "https://p.scdn.co/mp3-preview/6a78e9a3193b6f73617174db02acaa999f988918?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:2BHj31ufdEqVK5CkYDp9mA"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1LZEQNv7sE11VDY3SdxQeN"
              },
              "href": "https://api.spotify.com/v1/artists/1LZEQNv7sE11VDY3SdxQeN",
              "id": "1LZEQNv7sE11VDY3SdxQeN",
              "name": "Bee Gees",
              "type": "artist",
              "uri": "spotify:artist:1LZEQNv7sE11VDY3SdxQeN"
            }
          ],
          "available_markets": [
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GH",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JP",
            "KE",
            "KH",
            "KR",
            "KW",
            "LB",
            "LK",
            "LT",
            "LU",
            "LV",
            "MA",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NG",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SN",
            "SV",
            "TH",
            "TN",
            "TR",
            "TT",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4vAhQeeWkSjVn0p5GAaLBx"
          },
          "href": "https://api.spotify.com/v1/albums/4vAhQeeWkSjVn0p5GAaLBx",
          "id": "4vAhQeeWkSjVn0p5GAaLBx",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273324045726c4b0deb6cb7c875",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02324045726c4b0deb6cb7c875",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851324045726c4b0deb6cb7c875",
              "width": 64
            }
          ],
          "name": "How Can You Mend A Broken Heart",
          "release_date": "2020-11-20",
          "release_date_precision": "day",
          "total_tracks": 25,
          "type": "album",
          "uri": "spotify:album:4vAhQeeWkSjVn0p5GAaLBx"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1LZEQNv7sE11VDY3SdxQeN"
            },
            "href": "https://api.spotify.com/v1/artists/1LZEQNv7sE11VDY3SdxQeN",
            "id": "1LZEQNv7sE11VDY3SdxQeN",
            "name": "Bee Gees",
            "type": "artist",
            "uri": "spotify:artist:1LZEQNv7sE11VDY3SdxQeN"
          }
        ],
        "available_markets": [
          "AE",
          "AL",
          "AR",
          "AT",
          "AU",
          "BA",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "BY",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GH",
          "GR",
          "GT",
          "HK",
          "HN",
          "HR",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JP",
          "KE",
          "KH",
          "KR",
          "KW",
          "LB",
          "LK",
          "LT",
          "LU",
          "LV",
          "MA",
          "ME",
          "MK",
          "MT",
          "MX",
          "MY",
          "NG",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "SA",
          "SE",
          "SG",
          "SI",
          "SK",
          "SN",
          "SV",
          "TH",
          "TN",
          "TR",
          "TT",
          "TW",
          "UA",
          "US",
          "UY",
          "VN",
          "XK",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 285373,
        "explicit": false,
        "external_ids": {
          "isrc": "USRH10721057"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5ubvP9oKmxLUVq506fgLhk"
        },
        "href": "https://api.spotify.com/v1/tracks/5ubvP9oKmxLUVq506fgLhk",
        "id": "5ubvP9oKmxLUVq506fgLhk",
        "is_local": false,
        "name": "Stayin Alive",
        "popularity": 77,
        "preview_url": null,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:5ubvP9oKmxLUVq506fgLhk"
      }
    ],
    "limit": 10,
    "next": "https://api.spotify.com/v1/search?query=stay&type=track&offset=10&limit=10",
    "offset": 0,
    "previous": null,
    "total": 250006
  }
}''';

  Map<String, dynamic> json = jsonDecode(test);
  List<dynamic> parsing = json['tracks']['items'];

  List<Music>? musicList = [];
  for(int i = 0; i < parsing.length; i++) {
    Music music = Music.fromJson(parsing[i]);
    musicList.add(music);
  }

  // 중복 제거
  final id = musicList.map((e) => e.name).toSet();
  musicList.retainWhere((x) => id.remove(x.name));

  return musicList;
}